---
- name: Ensure EPICS MCA packages are installed
  package:
    name: "{{ epics_mca_packages }}"
    state: present
  become: true
  register: package_get_result
  until: package_get_result is success
  retries: 5
  delay: 2
