---
- name: Restart Zabbix service
  block:
    - name: Restart Zabbix service
      systemd:
        name: zabbix-agent
        state: restarted
  become: true
  ignore_errors: "{{ zabbix_ignore_systemd_errors }}"
  rescue:
    - name: Show warning to user if systemd fails
      pause:
        seconds: 1
        echo: false
        prompt: "Could not reload Zabbix Agent systemd service. Probably running in Docker? Continuing anyway ..."
