---

global_role_cs_studio: true
global_role_sirius_bbb: true
global_role_octave: true
global_role_epics_mca: true
global_role_desktop_settings: true
global_role_visual_studio_code: true

# === Services
glusterfs_service_server: "glusterd"

# === apt packages versions ===

pkg_version_zabbix_agent: "1:5.0.8+dfsg-1"
pkg_version_autofs: "5.1.7*"
pkg_version_ntp: "1:4.2.8*"
pkg_version_octave: "6.2.0*"
pkg_version_liboctave_dev: "6.2.0*"
pkg_version_epstool: "3.09*"
pkg_version_bzip2: "1.0.8*"
pkg_version_binutils: "2.35*"
pkg_version_epics_dev: "3.15.6*"
pkg_version_epics_pcas_dev: "3.15.6*"
pkg_version_libtool: "2.4.6*"
pkg_version_make: "4.3*"
pkg_version_autoconf: "2.69*"
pkg_version_automake: "1:1.16*"