---
- hosts: docker_servers
  remote_user: server
  become: true
  become_method: su
  become_user: root

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      vars:
        possible_var_files:
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_os_family }}.yml"
      loop: "{{ q('first_found', possible_var_files, errors='ignore') }}"

  roles:
    - { role: geerlingguy.repo-epel, when: ansible_os_family == 'RedHat' }
    - { role: geerlingguy.pip }
    - { role: geerlingguy.docker }

  vars:
    pip_install_packages:
      - name: docker

  tasks:
    - name: Create docker certs.d/ for the internal registry
      file:
        path: "/etc/docker/certs.d/{{ docker_registry_server }}/"
        state: directory
        mode: "0755"

    - name: Copy self signed crt to the client machine
      copy:
        src: "/etc/docker/certs.d/{{ docker_registry_server }}/ca.crt"
        dest: "/etc/docker/certs.d/{{ docker_registry_server }}/ca.crt"
        mode: 0644

    - name: "Adding existing user {{ ansible_ssh_user }} to group sudo"
      user:
        name: "{{ ansible_ssh_user }}"
        groups: docker
        append: yes

    - name: "Define swarm join token"
      set_fact:
        docker_swarm_join_token: "{{ lookup('env','SWARM_JOIN_TOKEN') }}"
        when: docker_swarm_join_token is not defined

    - debug:
        msg: "Swarm join token {{ docker_swarm_join_token }} ."

    - name: "Join swarm"
      community.general.docker_swarm:
        state: join
        join_token: "{{ docker_swarm_join_token }}"
        remote_addrs: [ "{{ docker_swarm_join_node }}" ]
      when: docker_swarm_join_token is defined and docker_swarm_join_token and docker_swarm_join_node is defined

    - name: Get info on Docker Swarm and filtered list of registered nodes
      community.general.docker_swarm_info:
      register: docker_swarm_info

    - name: "Swarm status:"
      debug:
        var: docker_swarm_info
