---
# DEPRECATED PLAYBOOK
- hosts: nfs_servers
  remote_user: sirius
  become: true

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      vars:
        possible_var_files:
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_os_family }}.yml"
      loop: "{{ q('first_found', possible_var_files, errors='ignore') }}"

  tasks:
    - import_role:
        name: lnls-ans-role-users
    - import_role:
        name: lnls-ans-role-nfsserver
    - import_role:
        name: lnls-ans-role-clone-install
      vars:
        clone_install_repos: "{{ lookup('vars', 'clone_install_repos_servnfs', default=[]) }}"
    - import_role:
        name: lnls-ans-role-clone-install
      vars:
        clone_install_repos: "{{ lookup('vars', 'clone_install_repos_sirius_screens', default=[]) }}"
