---
collections:
  - name: ansible.posix
    version: 1.1.1
  - name: community.general
    version: 2.0.0

roles:
  - name: geerlingguy.docker
    version: 3.0.0
  - name: geerlingguy.pip
    version: 2.0.0
  - name: geerlingguy.repo-epel
    version: 3.0.0
