---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 4.8.11

roles:
  - name: geerlingguy.docker
    version: 7.1.0
  - name: geerlingguy.pip
    version: 3.0.3
  - name: geerlingguy.repo-epel
    version: 3.1.1
