---
gas_docker_BbB_base_template_dir: ~/templates
gas_docker_BbB_settings_defaults: &gas_docker_BbB_settings_defaults
    ARAMP_TELNET_PORT: ""
    ARAMP_IP: "IA-16RaBbB-CO-SerEthConv"
    ARAMP_IMAGE_BASE: "dockerregistry.lnls-sirius.com.br/gas/ar-amp-epics-ioc"
    ARAMP_IMAGE_TAG: "v1.0.6-rc1-base-3.15-debian-9.13"
    ARAMP_CONTAINER_NAME: "ar-amp-epics-ioc"
    ARAMP_AUTOSAVE_DIR: "/storage/common/autosave/IA-16RaBbB-CO-IOCSrv"
    ARAMP_AREA_PREFIX: "SI-Glob:"
    ARAMP_PLACEMENT:
      - node.hostname != CA-RaCtrl-CO-Srv-1
      - node.hostname != LA-RaCtrl-CO-Srv-1
      - node.hostname != TA-TiRack-CO-FWSrv-1

gas_docker_BbB_settings:
  # AR Amplifier
  - <<: *gas_docker_BbB_settings_defaults
    STACK_NAME: "BbB-Glob-H"
    ARAMP_DEVICE: "75250AM2"
    ARAMP_DEVICE_PREFIX: "DI-BbBAmpH:"
    ARAMP_INSTANCE: "ARAmp-SI-Glob-DI-BbBAmpH"
    ARAMP_PORT: "4001"

  - <<: *gas_docker_BbB_settings_defaults
    STACK_NAME: "BbB-Glob-V"
    ARAMP_DEVICE: "75A400"
    ARAMP_DEVICE_PREFIX: "DI-BbBAmpV:"
    ARAMP_INSTANCE: "ARAmp-SI-Glob-DI-BbBAmpV"
    ARAMP_PORT: "4002"
