# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "debian.stretch" => "192.168.33.11",
}

Vagrant.configure("2") do |config|
  hosts.each do |name, ip|
    config.vm.define name do |machine|
      if name.eql? "debian.stretch" then
        machine.vm.box = "debian/stretch64"
      end
      machine.vm.hostname = "%s" % name
      machine.vm.network :private_network, ip: ip
      machine.vm.provider "virtualbox" do |v|
          v.name = name
          v.customize ["modifyvm", :id, "--memory", 256]
      end
    end
  end
end
