---
__epics_packages:
  - "epics-dev{{ (pkg_version_epics_dev | length > 0) | ternary('=' + pkg_version_epics_dev, '') }}"
  - "epics-pcas-dev{{ (pkg_version_epics_pcas_dev | length > 0) | ternary('=' + pkg_version_epics_pcas_dev, '') }}"

__epics_pip_packages:
  - "setuptools{{ (pkg_version_setuptools | length > 0) | ternary('==' + pkg_version_setuptools, '') }}"
  - "psutil{{ (pkg_version_psutil | length > 0) | ternary('==' + pkg_version_psutil, '') }}"
  - "pcaspy{{ (pkg_version_pcaspy | length > 0) | ternary('==' + pkg_version_pcaspy, '') }}"

__pip_executable: pip-sirius

__pip2_executable: pip
