---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

- name: Set default value for conda_packages_dependencies
  set_fact:
    conda_packages_dependencies: "{{ __conda_packages_dependencies | default([]) }}"
  when: "conda_packages_dependencies is not defined"

- name: Include platform specific tasks
  include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - 'task-{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - 'task-{{ ansible_distribution }}.yml'
        - 'task-{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/tasks'

- name: "Define conda variables relative to {{ conda_prefix }}"
  set_fact:
    conda_python_executable: "{{ conda_prefix }}/bin/python"
    conda_python_pip_executable: "{{ conda_prefix }}/bin/pip"
    conda_repos_path: "{{ conda_prefix }}/repos" # where we clone and install external repositories

- name: Include conda environment setup tasks
  include_tasks: "conda-environment.yml"

  # TODO: We are using for compatibilty reasons (python shebang)
- name: Link the environment executable to python-sirius
  file:
    state: link
    src: python
    dest: "{{ conda_prefix }}/bin/python-sirius"
    group: "{{ conda_group | default(omit) }}"
