---
- name: Install apt dependency packages
  apt:
    name: "{{ conda_packages_dependencies }}"
    state: present
    update_cache: true
    # We only need this as we might have expired signatures
    # that could prevent us from executing this. The next task
    # should fix this is that's the case, is not, it will fail for
    # some other reason
    allow_unauthenticated: true
  # In some cases, we might have an invalid signature, preventing
  # us from executing this. Ignore failures here and if something
  # doesn't work on the next task we deal with it manually
  failed_when: false
  become: true
  register: apt_result
  until: apt_result is success
  retries: 5
  delay: 2
