# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.apt_proxy_server is defined %}
RUN if [ $(command -v apt-get) ]; then echo "Acquire::http { Proxy \"http://{{ item.apt_proxy_server }}\"; }" > /etc/apt/apt.conf.d/proxy; fi
{% endif %}

RUN \
{% if item.dns_servers is defined and item.dns_servers %}
    {% for dns in item.dns_servers %}
        {% if dns|length %}
            echo "nameserver {{ dns }}" >> /etc/resolv.conf && \
        {% endif %}
    {% endfor %}
    {% if item.dns_search is defined %}
            echo "search {{ item.dns_search }}" >> /etc/resolv.conf && \
    {% endif %}
{% endif %}
    if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python sudo bash ca-certificates && apt-get clean; \
    elif [ $(command -v dnf) ]; then dnf makecache && dnf --assumeyes install python sudo python-devel python2-dnf bash && dnf clean all; \
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    elif [ $(command -v zypper) ]; then zypper refresh && zypper install -y python sudo bash python-xml && zypper clean -a; \
    elif [ $(command -v apk) ]; then apk update && apk add --no-cache python sudo bash ca-certificates; \
    elif [ $(command -v xbps-install) ]; then xbps-install -Syu && xbps-install -y python sudo bash ca-certificates && xbps-remove -O; fi
