---
galaxy_info:
  author: Lucas Russo
  description: Ansible role to install EPICS base and extra packages
  company: CNPEM - LNLS
  license: BSD
  min_ansible_version: 4.0

  platforms:
    - name: Debian
      versions:
        - buster
        - stretch
        - jessie
        - bullseye
    - name: Ubuntu
      versions:
        - xenial
        - trusty

dependencies: []
