---
- name: Converge
  hosts: all

  pre_tasks:
    - name: create test users
      become: true
      user:
        name: '{{ item }}'
        state: present
        home: '/home/{{ item }}'
        createhome: true
      with_items:
        - test_usr
        - test_usr2
        - test_usr3

    - name: install gnupg2 (apt)
      become: true
      apt:
        name: gnupg2
        state: present
      when: ansible_pkg_mgr == 'apt'

    - name: install extension cli dependencies (zypper)
      become: true
      zypper:
        name: libX11-xcb1
        state: present
      when: ansible_pkg_mgr == 'zypper'

    - name: install extension cli dependencies (apt)
      become: true
      apt:
        name: libx11-xcb1
        state: present
      when: ansible_pkg_mgr == 'apt'

  roles:
    - role: lnls-ans-role-visual-studio-code
      visual_studio_code_users:
        - username: test_usr
          visual_studio_code_extensions:
            - ms-python.python
            - wholroyd.jinja
          visual_studio_code_settings: {
            "editor.rulers": [80, 100, 120],
            "editor.renderWhitespace": true
          }
        - username: test_usr2
          visual_studio_code_extensions: []
          visual_studio_code_settings: {}
        - username: test_usr3

  post_tasks:
    - name: install which
      package:
        name: which
        state: present
      when: ansible_pkg_mgr in ('yum', 'dnf', 'zypper')
