---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  register: apt_update_cache_result
  until: apt_update_cache_result is success
  retries: 5
  delay: 2

- name: Install Glusterfs packages
  apt:
    name: "{{ glusterfs_packages }}"
    state: present
  become: true
  register: apt_result
  until: apt_result is success
  retries: 5
  delay: 2
