---
- name: Ensure PIP Python packages are installed
  pip:
    name: "{{ qt_pip_packages }}"
    state: "{{ qt_pip_packages_state }}"
    executable: "{{ pip_executable }}"
  become: true
  register: qt_pip_packages_result
  until: qt_pip_packages_result is success
  retries: 5
  delay: 2
