---
- name: Ensure no PyQt PIP versions are installed
  pip:
    name: "{{ item | regex_replace('==.*$', '') }}"
    state: absent
    executable: "{{ pip_executable }}"
  become: true
  register: qt_pip_packages_result
  until: qt_pip_packages_result is success
  retries: 5
  delay: 2
  with_items:
    - "{{ qt_pip_packages }}"
