---
- name: Install pendency packages
  package:
    name: "{{ dep_packages }}"
    state: present
  become: true
  register: package_result
  until: package_result is success
  retries: 5
  delay: 2
