---
zabbix_server_ips:
  - 10.0.38.46
  - 10.0.38.59

zabbix_server_active_ips:
  - 10.0.38.46
  - 10.0.38.59

zabbix_config_file_preferences:
  - path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server="
    line: "Server={{ zabbix_server_ips | join(', ') }}"

  - path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^ServerActive="
    line: "ServerActive={{ zabbix_server_active_ips | join(', ') }}"
