---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

- name: Define Python executable
  set_fact:
    python_executable: "{{ __python_executable | default('python') }}"
  when: python_executable is not defined

- name: Define PIP executable
  set_fact:
    pip_executable: "{{ __pip_executable | default(omit) }}"
  when: pip_executable is not defined

- name: Define Recommended PIP packages
  set_fact:
    pydm_recommended_apps_pip: "{{ __pydm_recommended_apps_pip | default([]) | list }}"
  when: pydm_recommended_apps_pip is not defined

# Setup/install tasks
- include_tasks: setup-pydm.yml
