---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  register: apt_update_cache_result
  until: apt_update_cache_result is success
  retries: 5
  delay: 2

- name: Ensure Desktop packages are installed
  apt:
    name: "{{ desktop_settings_packages }}"
    state: "{{ desktop_settings_packages_state }}"
    install_recommends: "{{ desktop_settings_install_recommends }}"
    default_release: "{{ desktop_settings_default_release | default(omit) }}"
  become: true
  register: apt_packages_result
  until: apt_packages_result is success
  retries: 5
  delay: 2

- name: Ensure systemd-resolved is used if available
  block:
    - name: Ensure systemd-resolved is used if available
      systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items:
        - "systemd-resolved"
  become: true
  ignore_errors: "{{ desktop_settings_ignore_systemd_resolved_errors }}"
  rescue:
    - name: Show warning to user if systemd-resolved fails
      pause:
        seconds: 1
        echo: false
        prompt: "Could not start systemd-resolved service. Probably not available. Continuing anyway ..."
