---
- hosts: ioc_ps_srv
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service

    services_to_run_fams:
      - sirius-ioc-bo-ps-dipole-1.service
      - sirius-ioc-bo-ps-dipole-2.service
      - sirius-ioc-bo-ps-quadrupole-qd.service
      - sirius-ioc-bo-ps-quadrupole-qf.service
      - sirius-ioc-bo-ps-sextupole-sf.service
      - sirius-ioc-bo-ps-sextupole-sd.service

    services_to_run_corrs:
      - sirius-ioc-bo-ps-correctors-ia01
      - sirius-ioc-bo-ps-correctors-ia02
      - sirius-ioc-bo-ps-correctors-ia04
      - sirius-ioc-bo-ps-correctors-ia05
      - sirius-ioc-bo-ps-correctors-ia07
      - sirius-ioc-bo-ps-correctors-ia08
      - sirius-ioc-bo-ps-correctors-ia10
      - sirius-ioc-bo-ps-correctors-ia11
      - sirius-ioc-bo-ps-correctors-ia13
      - sirius-ioc-bo-ps-correctors-ia14
      - sirius-ioc-bo-ps-correctors-ia16
      - sirius-ioc-bo-ps-correctors-ia17
      - sirius-ioc-bo-ps-correctors-ia20

    services_to_run_diags:
      - sirius-ioc-bo-ps-diag.service

  tasks:

    - name: "Run {{ role_to_run }} role for BO fams"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "'{{ item }}'"
      with_items:
        - "{{ services_to_run_fams }}"
      when:
        - ansible_host == ioc_bo_ps_fams_srv_host
        - services_to_run_fams is defined and services_to_run_fams | length > 0

    - name: "Run {{ role_to_run }} role for BO corrs"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "'{{ item }}'"
      with_items:
        - "{{ services_to_run_corrs }}"
      when:
        - ansible_host == ioc_bo_ps_corrs_srv_host
        - services_to_run_corrs is defined and services_to_run_corrs | length > 0

    - name: "Run {{ role_to_run }} role for BO diags"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "'{{ item }}'"
      with_items:
        - "{{ services_to_run_diags }}"
      when:
        - ansible_host == ioc_bo_ps_diags_srv_host
        - services_to_run_diags is defined and services_to_run_diags | length > 0
