---
- hosts: ioc_ps_srv
  remote_user: sirius

  vars:
    role_to_run: lnls-ans-role-ctrl-service

    services_to_run_spect:
      - sirius-ioc-li-ps-spect.service

    services_to_run_quads:
      - sirius-ioc-li-ps-qd1.service
      - sirius-ioc-li-ps-qd2.service
      - sirius-ioc-li-ps-qf1.service
      - sirius-ioc-li-ps-qf2.service
      - sirius-ioc-li-ps-qf3.service

    services_to_run_corrs:
      - sirius-ioc-li-ps-ch1.service
      - sirius-ioc-li-ps-ch2.service
      - sirius-ioc-li-ps-ch3.service
      - sirius-ioc-li-ps-ch4.service
      - sirius-ioc-li-ps-ch5.service
      - sirius-ioc-li-ps-ch6.service
      - sirius-ioc-li-ps-ch7.service
      - sirius-ioc-li-ps-cv1.service
      - sirius-ioc-li-ps-cv2.service
      - sirius-ioc-li-ps-cv3.service
      - sirius-ioc-li-ps-cv4.service
      - sirius-ioc-li-ps-cv5.service
      - sirius-ioc-li-ps-cv6.service
      - sirius-ioc-li-ps-cv7.service

    services_to_run_lens:
      - sirius-ioc-li-ps-lensrev.service
      - sirius-ioc-li-ps-lens-01.service
      - sirius-ioc-li-ps-lens-02.service
      - sirius-ioc-li-ps-lens-03.service
      - sirius-ioc-li-ps-lens-04.service

    services_to_run_solenoids:
      - sirius-ioc-li-ps-solenoid-01.service
      - sirius-ioc-li-ps-solenoid-02.service
      - sirius-ioc-li-ps-solenoid-03.service
      - sirius-ioc-li-ps-solenoid-04.service
      - sirius-ioc-li-ps-solenoid-05.service
      - sirius-ioc-li-ps-solenoid-06.service
      - sirius-ioc-li-ps-solenoid-07.service
      - sirius-ioc-li-ps-solenoid-08.service
      - sirius-ioc-li-ps-solenoid-09.service
      - sirius-ioc-li-ps-solenoid-10.service
      - sirius-ioc-li-ps-solenoid-11.service
      - sirius-ioc-li-ps-solenoid-12.service
      - sirius-ioc-li-ps-solenoid-13.service
      - sirius-ioc-li-ps-solenoid-14.service
      - sirius-ioc-li-ps-solenoid-15.service
      - sirius-ioc-li-ps-solenoid-16.service
      - sirius-ioc-li-ps-solenoid-17.service
      - sirius-ioc-li-ps-solenoid-18.service
      - sirius-ioc-li-ps-solenoid-19.service
      - sirius-ioc-li-ps-solenoid-20.service
      - sirius-ioc-li-ps-solenoid-21.service

    services_to_run_conv:
      - sirius-ioc-li-ps-conv.service

  tasks:

    - name: "Run {{ role_to_run }} role for LI spect"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "'{{ item }}'"
      with_items:
        - "{{ services_to_run_spect }}"
      when:
        - ansible_host == ioc_li_ps_spect_srv_host
        - services_to_run_spect is defined and services_to_run_spect | length > 0

    - name: "Run {{ role_to_run }} role for LI quads"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "'{{ item }}'"
      with_items:
        - "{{ services_to_run_quads }}"
      when:
        - ansible_host == ioc_li_ps_quads_srv_host
        - services_to_run_quads is defined and services_to_run_quads | length > 0

    - name: "Run {{ role_to_run }} role for LI corrs"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "'{{ item }}'"
      with_items:
        - "{{ services_to_run_corrs }}"
      when:
        - ansible_host == ioc_li_ps_corrs_srv_host
        - services_to_run_corrs is defined and services_to_run_corrs | length > 0

    - name: "Run {{ role_to_run }} role for LI lens"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "'{{ item }}'"
      with_items:
        - "{{ services_to_run_lens }}"
      when:
        - ansible_host == ioc_li_ps_lens_srv_host
        - services_to_run_lens is defined and services_to_run_lens | length > 0

    - name: "Run {{ role_to_run }} role for LI solenoids"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "'{{ item }}'"
      with_items:
        - "{{ services_to_run_solenoids }}"
      when:
        - ansible_host == ioc_li_ps_solenoids_srv_host
        - services_to_run_solenoids is defined and services_to_run_solenoids | length > 0

    - name: "Run {{ role_to_run }} role for LI conversion"
      include_role:
        name: "{{ role_to_run }}"
      vars:
        ctrl_service_name: "'{{ item }}'"
      with_items:
        - "{{ services_to_run_conv }}"
      when:
        - ansible_host == ioc_li_ps_conv_srv_host
        - services_to_run_conv is defined and services_to_run_conv | length > 0
