---
- name: "Ensure repository {{ item.repo_name }} is cloned"
  git:
    repo: "{{ item.org_url }}/{{ item.repo_name }}"
    dest: "{{ item.clone_path }}/{{ item.repo_name }}"
    version: "{{ item.repo_version | default('master') }}"
    accept_hostkey: "{{ item.git_accept_hostkey | default(omit) }}"
    ssh_opts: "{{ item.git_ssh_opts | default(omit) }}"
    force: "{{ item.force_version | default(false) }}"
  register: git_result
  when: item.install_via_makefile is defined and
        (item.install_via_makefile | bool)

- name: "Define {{ item.repo_name }} chdir variable"
  set_fact:
    repo_install_chdir: "{{ item.install_chdir | default('') }}"

- name: "Define {{ item.repo_name }} egg name variable"
  set_fact:
    repo_egg_name: "{{ item.install_chdir | default(item.repo_name) }}"

- name: "Install {{ item.repo_name }} via Makefile"
  make:
    chdir: "{{ item.clone_path }}/{{ item.repo_name }}/{{ repo_install_chdir }}"
    target: "{{ item.make_install_target | default('install') }}"
    params: "{{ item.make_install_opts | default({}) }}"
  become: true
  when: item.install_via_makefile is defined and
        (item.install_via_makefile | bool) and
        git_result.changed

# REMOVED: This task should not be used anymore, migrate to a conda environment
# - name: "Install {{ item.repo_name }} via setup.py"
