---
__sirius_apps_packages:
  - epics-extensions-dev
  # DEPRECATED: dead project not available on Debian 11+, we should not use this - winswitch
  - xvfb
  - bc
  - libblas-dev
  - liblapack-dev
  - libgsl-dev
  - rsync
  - htop

__sirius_apps_pip_packages:
  - pyvisa
  - pyvisa-py

__python_executable: python-sirius

__pip_executable: pip-sirius
