---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      ignore_errors: true
      paths:
        - '{{ role_path }}/vars'

# Setup
- include_tasks: setup-Debian.yml
  when:
    - ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when:
    - ansible_os_family == 'RedHat'

- name: Create conda group for multi user access
  group:
    name: conda
    state: present
    system: yes

- name: Update conda permissions
  file:
    mode: 'u=rwx,g=rwx,o=rx'
    group: conda
    path: "{{ conda_install_path }}"
    recurse: yes

- name: Install conda profile
  template:
    src: conda-profile.sh.j2
    dest: /etc/profile.d/conda-profile.sh
    mode: 'u=rwx,g=rx,o=rx'
