---
- name: install dependencies (zypper)
  become: true
  zypper:
    name: which
    state: present

- name: install key (zypper)
  become: true
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: write repo configuration (zypper)
  become: true
  template:
    src: vscode.repo.j2
    dest: '/etc/zypp/repos.d/vscode.repo'
    mode: 'u=rw,go='
    owner: root
    group: root

- name: install VS Code (zypper)
  become: true
  zypper:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
    state: present
