---
- name: install dependencies (apt)
  become: true
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - "libgtk2.0-0{{ (pkg_version_libgtk2_0_0 | length > 0) | ternary('=' + pkg_version_libgtk2_0_0, '') }}"
      - "libxss1{{ (pkg_version_libxss1 | length > 0) | ternary('=' + pkg_version_libxss1, '') }}"
    state: present

- name: install key (apt)
  become: true
  apt_key:
    url: 'https://packages.microsoft.com/keys/microsoft.asc'
    state: present

- name: install VS Code repo (apt)
  become: true
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present

- name: install VS Code (apt)
  become: true
  apt:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
    state: present
