---
- name: Ensure Visual Studio packages are installed
  package:
    name: "{{ visual_studio_packages }}"
    state: present
  become: true
  register: package_get_result
  until: package_get_result is success
  retries: 5
  delay: 2
