---
vars:
  apt_proxy_server: "${APT_PROXY_SERVER}"

dependency:
  name: galaxy
  collections:
    - name: community.docker
      version: 2.0.2

driver:
  name: docker

lint: |
  set -xe
  yamllint .
  ansible-lint

platforms:
  - name: lnls-ans-role-conda-packages-debian11
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-debian11-ansible}"
    command: ${MOLECULE_DOCKER_COMMAND:-/lib/systemd/systemd}
    groups:
      - default_group
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    build_image: false
    dns_servers: ["${DNS_SERVER1:-8.8.8.8}", "${DNS_SERVER2:-8.8.4.4}"]

  - name: lnls-ans-role-conda-packages-debian9
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-debian9-ansible}"
    command: ${MOLECULE_DOCKER_COMMAND:-/lib/systemd/systemd}
    groups:
      - default_group
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    build_image: false
    dns_servers: ["${DNS_SERVER1:-8.8.8.8}", "${DNS_SERVER2:-8.8.4.4}"]

provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../Vagrant/inventory/group_vars/
    group_vars:
      default_group:

verifier:
  name: ansible
