---
# APT repositories
__repository_keys:
  - name: Debian VSCode key
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/vscode-debian.gpg

__repository_apt:
  - name: Debian VScode
    baseurl: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    description: "Debian Stretch VScode"
    file: debian-vscode
    state: present

  - name: Debian Bullseye-Backports Main
    baseurl: "deb http://deb.debian.org/debian bullseye-backports main"
    description: "Debian Bullseye-Backports Main"
    file: debian-bullseye-backports-main
    state: present
