---
# Package versions for PIP. Leave empty for the latest
pkg_version_setuptools: ""

sirius_apps_hlacon_conda_python_version: "3.8"

sirius_apps_hlacon_conda_environment_path: /opt/conda/envs/cons

# Specify if we want to remove HLACON packages from system python
# or not
sirus_apps_hlacon_remove_from_system: true

# Conda packages to install
# Example
#
# sirius_apps_hlacon_conda_packages:
#   - qt==5.12.9
#   - pyqt==5.12.3
#   - pydm==1.10.4

sirius_apps_hlacon_conda_packages: []

# PIP packages to install
# Example
#
# sirius_apps_hlacon_pip_packages:
#   - siriushlacon==2.0.2

sirius_apps_hlacon_pip_packages: []

# Executable names to install
# Example
#
# sirius_apps_hlacon_executables:
#   - sirius-hla-as-ap-bbb-monitor
#   - sirius-hla-as-ap-conlauncher
#   - sirius-hla-as-ap-countingpru
#   - sirius-hla-as-ap-mbtemp
#   - sirius-hla-as-ap-pctrl
#   - sirius-hla-as-ps-regatron-individual
#   - sirius-hla-as-ps-regatron
#   - sirius-hla-as-pu-spixconv
#   - sirius-hla-as-va-agilent4uhv-device
#   - sirius-hla-as-va-agilent4uhv
#   - sirius-hla-as-va-mks937b
#   - sirius-hla-bo-va-agilent4uhv-overview
#   - sirius-hla-bo-va-mks937b-overview
#   - sirius-hla-si-va-agilent4uhv-overview
#   - sirius-hla-si-va-mks937b-overview
#   - sirius-hla-tb-va-agilent4uhv-overview
#   - sirius-hla-tb-va-mks937b-overview
#   - sirius-hla-ts-va-agilent4uhv-overview
#   - sirius-hla-ts-va-mks937b-overview

sirius_apps_hlacon_executables: []
