---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Include molecule overrides
      include_vars: "{{ lookup('first_found', possible_var_files) }}"
      vars:
        possible_var_files:
          - "../../../../group_vars/molecule_overrides.yml"

    - name: Include distribution-dependent variables
      include_vars: "{{ lookup('first_found', possible_var_files) }}"
      vars:
        possible_var_files:
          - "../../../../group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "../../../../group_vars/{{ ansible_distribution }}.yml"
          - "../../../../group_vars/{{ ansible_os_family }}.yml"
          - "../../../../group_vars/all"

    - name: Apt Proxy entry
      template:
        src: proxy.j2
        dest: /etc/apt/apt.conf.d/proxy
        owner: root
        group: root
        mode: 0644
      when: >
          ansible_os_family == 'Debian' and
          molecule_yml.vars.apt_proxy_server is defined and
          molecule_yml.vars.apt_proxy_server
      vars:
       apt_proxy_server: "{{ molecule_yml.vars.apt_proxy_server }}"


  roles:
    - role: lnls-ans-role-conda
