---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Apt Proxy entry
      template:
        src: proxy.j2
        dest: /etc/apt/apt.conf.d/proxy
        owner: root
        group: root
        mode: 0644
      when: >
          ansible_os_family == 'Debian' and
          molecule_yml.vars.apt_proxy_server is defined and
          molecule_yml.vars.apt_proxy_server
      vars:
       apt_proxy_server: "{{ molecule_yml.vars.apt_proxy_server }}"


  roles:
    - role: lnls-ans-role-conda
