---
vars:
  apt_proxy_server: "${APT_PROXY_SERVER}"

dependency:
  name: galaxy
  collections:
    - name: community.docker
      version: 1.5.0
  options:
    role-file: requirements.yml
    collection-file: requirements.yml

driver:
  name: docker

lint: |
  set -xe
  yamllint .
  ansible-lint

platforms:
  - name: lnls-ans-role-conda-instance-debian9
    image: "geerlingguy/docker-debian9-ansible"
    command: ${MOLECULE_DOCKER_COMMAND:-/lib/systemd/systemd}
    groups:
      - default_group
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    build_image: false
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]

  - name: lnls-ans-role-conda-instance-debian11
    image: "geerlingguy/docker-debian11-ansible"
    command: ${MOLECULE_DOCKER_COMMAND:-/lib/systemd/systemd}
    groups:
      - default_group
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    build_image: false
    dns_servers: ["${DNS_SERVER1}", "${DNS_SERVER2}"]

provisioner:
  name: ansible

verifier:
  name: ansible
