---
- hosts: control_room:control_room_tv:control_room_linac_opis:control_room_new_pcs:con:elp
  remote_user: sirius
  become: true
  gather_facts: true
  vars:
    install_terminfo_kitty: false

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      vars:
        possible_var_files:
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_os_family }}.yml"
      loop: "{{ q('first_found', possible_var_files, errors='ignore') }}"

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Install Kitty terminfo
      include_tasks: tasks/setup-kitty.yml
      when: install_terminfo_kitty

    - name: Include role lnls-ans-role-users
      include_role:
        name: lnls-ans-role-users
      when: global_role_users | default(true) | bool

    - name: Include role lnls-ans-role-network
      include_role:
        name: lnls-ans-role-network
      when: global_network_role | default(true) | bool

    - name: Include role lnls-ans-role-nvidia-driver
      include_role:
        name: lnls-ans-role-nvidia-driver
      when: global_import_nvidia_driver_role | default(false) | bool

    - name: Include role lnls-ans-role-ntp
      include_role:
        name: lnls-ans-role-ntp

    - name: Include role lnls-ans-role-zabbix
      include_role:
        name: lnls-ans-role-zabbix

    - name: Include role lnls-ans-role-epics
      include_role:
        name: lnls-ans-role-epics

    - name: Include role lnls-ans-role-epics7
      include_role:
        name: lnls-ans-role-epics7

    - name: Include role lnls-ans-role-cs-studio
      include_role:
        name: lnls-ans-role-cs-studio
      when: global_role_cs_studio | default(true) | bool

    - name: Include role lnls-ans-role-sirius-bbb
      include_role:
        name: lnls-ans-role-sirius-bbb
      when: global_role_sirius_bbb | default(true) | bool

    - name: Include role lnls-ans-role-octave
      include_role:
        name: lnls-ans-role-octave
      when: global_role_octave | default(true) | bool

    - name: Include role lnls-ans-role-epics-mca
      include_role:
        name: lnls-ans-role-epics-mca
      when: global_role_epics_mca | default(true) | bool

    - name: Call lnls-ans-role-conda-packages passing down variables for each environment
      include_tasks: tasks/setup-conda-environment.yml

    - name: Include role lnls-ans-role-sirius-hlacon
      include_role:
        name: lnls-ans-role-sirius-hlacon

    - name: Include role lnls-ans-role-apps
      include_role:
        name: lnls-ans-role-apps

    - name: Include role lnls-ans-role-sirius-hla
      include_role:
        name: lnls-ans-role-hla

    - name: Include role lnls-ans-role-desktop-apps
      include_role:
        name: lnls-ans-role-desktop-apps

    - name: Include role lnls-ans-role-desktop-settings
      include_role:
        name: lnls-ans-role-desktop-settings
      when: global_role_desktop_settings | default(true) | bool

    - name: Include role lnls-ans-role-visual-studio-code
      include_role:
        name: lnls-ans-role-apps
      when: global_role_visual_studio | default(false) | bool
