---
- hosts: vagrant
  remote_user: sirius
  become: true
  gather_facts: true
  vars:
    install_terminfo_kitty: false

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      vars:
        possible_var_files:
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_os_family }}.yml"
      loop: "{{ q('first_found', possible_var_files, errors='ignore') }}"

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Call lnls-ans-role-conda-packages passing down variables for each environment
      include_tasks: tasks/setup-conda-environment.yml
