---
- hosts: vagrant
  remote_user: sirius
  become: true
  gather_facts: true

  pre_tasks:
    - name: Include distribution-dependent variables
      include_vars: "{{ item }}"
      with_first_found:
        - files:
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_distribution }}.yml"
          - "../{{ inventory }}/group_vars/{{ ansible_os_family }}.yml"
          skip: true

  tasks:
    - debug:
        msg: "{{ epics_install_from_source | default('') }}"

    - name: Include role lnls-ans-role-epics
      include_role:
        name: lnls-ans-role-epics
