---
- hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Include distribution-dependent variables
      include_tasks: tasks/variables.yml

  tasks:
    - name: Include role lnls-ans-role-epics
      include_role:
        name: lnls-ans-role-epics
