---
- name: Converge
  hosts: all

  vars:

    # Remove LINAC IOC PS as it's a private repo
    sirius_apps_iocs:
      - name: Machine Applications
        org_url: https://github.com/lnls-sirius
        repo_name: machine-applications
        repo_version: "{{ pkg_version_machine_applications }}"
        clone_path: /tmp
        install_via_makefile: true
        force_version: true

    # Select which categories to install.
    sirius_apps_install_categories:
      - sirius_apps_dev_packages
      - sirius_apps_iocs
      - sirius_apps_mgmt

  pre_tasks:
    - name: Include molecule overrides
      include_vars: "{{ lookup('first_found', possible_var_files) }}"
      vars:
        possible_var_files:
          - "../../../../group_vars/molecule_overrides.yml"

    - name: Include distribution-dependent variables
      include_vars: "{{ lookup('first_found', possible_var_files) }}"
      vars:
        possible_var_files:
          - "../../../../group_vars/{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
          - "../../../../group_vars/{{ ansible_distribution }}.yml"
          - "../../../../group_vars/{{ ansible_os_family }}.yml"
          - "../../../../group_vars/all"

    - name: Apt Proxy entry
      template:
        src: proxy.j2
        dest: /etc/apt/apt.conf.d/proxy
        owner: root
        group: root
        mode: 0644
      when: >
          ansible_os_family == 'Debian' and
          molecule_yml.vars.apt_proxy_server is defined and
          molecule_yml.vars.apt_proxy_server
      vars:
       apt_proxy_server: "{{ molecule_yml.vars.apt_proxy_server }}"


  roles:
    - role: lnls-ans-role-sirius-apps
