# This will disable EPICS python from lnls-ans-role-epics
epics_install_python_packages: false

# Conda group name
conda_group: conda

conda_path: /opt/conda
conda_executable: /opt/conda/bin/conda
conda_profile: /opt/conda/etc/profile.d/conda.sh

conda_prefix: /opt/conda/envs/sirius
conda_python_version: '3.9.2'

conda_packages:
  - aiohttp=3.7.4
  - bottleneck=1.3.2
  - matplotlib=3.5.1
  - pyparsing=2.4.2
  - pyqt=5.12.3 # brings qt
  - pyqtgraph=0.11.0
  - pytest=6.2.4
  - pyvisa-py=0.3.1
  - pyvisa=1.10.1
  - QtAwesome=0.7.2

conda_pip_packages:
  - jupyterlab
  - jupyter_contrib_nbextensions
  - notebook
  - pcaspy==0.7.3
  - pydm==1.10.3
  - pyepics==3.4.0
  - timechart

conda_activate_templates:
  - src: sirius-activate.sh.j2
    dest: sirius-activate.sh

conda_deactivate_templates:
  - src: sirius-deactivate.sh.j2
    dest: sirius-deactivate.sh

conda_clone_install_make:
  - repo: "https://github.com/lnls-fac/mathphys.git"
    version: overwrite-make-variable
    targets: install
    force_version: true

  - repo: "https://github.com/lnls-sirius/dev-packages.git"
    version: master
    targets: install
    force_version: true
    cd: siriuspy

  - repo: "https://github.com/lnls-fac/lnls.git"
    version: master
    targets: install
    force_version: true

  - repo: "https://github.com/lnls-fac/trackcpp.git"
    version: master
    force_version: true
    targets: [ clean, install ]

  - repo: "https://github.com/lnls-fac/pyaccel.git"
    version: master
    targets: install
    force_version: true

  - repo: "https://github.com/lnls-fac/pymodels.git"
    version: master
    targets: install
    force_version: true

  - repo: "https://github.com/lnls-fac/apsuite.git"
    version: master
    targets: install
    force_version: true

  - repo: "https://github.com/lnls-sirius/hla.git"
    version: master
    targets: install
    force_version: true
    cd: pyqt-apps

  - repo: "https://github.com/lnls-fac/hlafac.git"
    version: master
    targets: install
    force_version: true

  - repo: "https://github.com/lnls-sirius/eth-bridge-pru-serial485.git"
    version: master
    targets: install
    force_version: true
    cd: client

  - repo: "https://github.com/lnls-sirius/machine-applications.git"
    version: master
    targets: install
    force_version: true

conda_app_executables:
  - name: jupyter-sirius
    command: jupyter notebook

  - name: ipython-sirius
    command: ipython

  - name: designer-sirius
    command: designer

  - name: sirius-hla-as-ap-launcher
    command: sirius-hla-as-ap-launcher.py
