---
- name: Restart Network Manager systemd service
  block:
    - name: Restart Network Manager systemd service
      systemd:
        name: NetworkManager
        state: restarted
  become: true
  ignore_errors: "{{ network_ignore_systemd_errors }}"
  rescue:
    - name: Show warning to user if systemd fails
      pause:
        seconds: 1
        echo: false
        prompt: "Could not restart NetworkManager systemd service. Probably running in Docker? Continuing anyway ..."
