---
- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400
  become: true
  register: apt_update_cache_result
  until: apt_update_cache_result is success
  retries: 5
  delay: 2

- name: Ensure Octave is installed
  apt:
    name: "{{ octave_packages }}"
    state: present
  become: true
  register: apt_get_result
  until: apt_get_result is success
  retries: 5
  delay: 2
